### ISSUE TITLE
Texture Saving seems outputting greyscale only?

### ISSUE THREAD

**Issue by enzyme69** [hsab/GrowthNodes#10]
<img width="857" alt="screen shot 2018-01-16 at 10 47 24 pm" src="https://user-images.githubusercontent.com/3952687/34987438-44895700-fb0f-11e7-8f31-ee965123b53a.png">

I am testing a simple node saving texture, so far I am getting just grayscale, even though I use the Color node.

**Comment by hsab** [comment]
This is the expected behavior since displacement in blender is only concerned with luminance/grayscale values and not color.
