### ISSUE TITLE
Possible to have Debug Print or Viewer node?

### ISSUE THREAD

**Issue by enzyme69** [hsab/GrowthNodes#11]
With some of Math operations, perhaps it is nice to have some kind of Debug Print or Viewer node, not sure how it works yet with Growth Nodes, but it might come in handy.

I can see there is Script Node, maybe that can actually print out values?

**Comment by hsab** [comment]
Script is really buggy. But will be fixed for the next release so user can write custom python scripts that manipulate the input sockets and output something using generic socket type. Debug is already implemented extensively but not fully tested so it's been disabled for this release and is planned for the next update. 

In regards to math operations, they should be showing up immediately in the nodetree. Refer to the image below:

 ![enter image description here](https://raw.githubusercontent.com/hsab/GrowthNodes/gifs/gifs/nodes.gif)

Will keep this open until the next release.

**Comment by hsab** [comment]
With the new release, the script node is semi functional. I'm gonna close this issue for now.
