### ISSUE TITLE
Growth Nodes with Blender 2.83 Voxel Remesher

### ISSUE THREAD

**Issue by enzyme69** [hsab/GrowthNodes#20]
I wonder if this addon can be updated for Blender 2.83 now that we have Voxel Remesher as modifier and also faster performance for sculpting mesh?

**Comment by hsab** [comment]
I just updated the master branch for 2.8. I tried to fix some of the leftover issues here and there but haven't really gotten to integrating the new remeshing functionality. Give it a try and let me know how it goes!
